---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workout-tracker-config
  namespace: workout-tracker
data:
  NODE_ENV: "production"
  JWT_ACCESS_EXPIRES_IN: "15m"
  JWT_REFRESH_EXPIRES_IN: "7d"
  FRONTEND_URL: "https://workout.home.lab"
