apiVersion: v1
kind: ConfigMap
metadata:
  name: workout-tracker-config
  namespace: workout-tracker
data:
  JWT_ACCESS_EXPIRES_IN: "15m"
  JWT_REFRESH_EXPIRES_IN: "7d"
  NODE_ENV: "production"
  FRONTEND_URL: "http://workout.home"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "workouttracker"
